### PR TITLE
Add icons

### PR DESCRIPTION
**Pull request by asangma**
* calculator
* grid
* sort-ascending
* sort-descending

### CODE REVIEW

**Comment by mpayson** [comment]
Hello @asangma,
I can't get the sort-ascending / sort-descending icons to display with their respective font classes. See the JS Bin example here: http://jsbin.com/luvikugito/edit?html,output.
Thank you!

**Comment by paulcpederson** [comment]
@mpayson they are not in the icon font yet. The entire font will need to be regenerated to pick up the additional classes.

**Comment by mpayson** [comment]
ah okay, thank you @paulcpederson

**Comment by asangma** [comment]
Thanks @paulcpederson!

**Pull request merged**
