### PR TITLE
removed third-nav

### PR DESCRIPTION
**Pull request by julio8a**
removed since this will be added as a tab modifier #1010

### CODE REVIEW

**Comment by paulcpederson** [comment]
So the idea is that when devs want a third nav without the tabbing they'll just use the tab classes with no `js-` hooks? We should probably document that if that's the case.

**Comment by macandcheese** [comment]
I think it would make sense to have "tabs" class contains styling and then "js-tabs" or something like that to opt in to the switching functionality.

**Comment by paulcpederson** [comment]
Yeah, I believe that's the current setup.

**Comment by julio8a** [comment]
merging this guy!

**Pull request merged**
