### PR TITLE
Added 'active' class to buttons

### LINKED ISSUE #985: Support Bootstrap's active button state
I expect Calcite to support `active` button states like bootstrap usually does: https://getbootstrap.com/docs/4.0/components/buttons/#active-state

### PR DESCRIPTION
**Pull request by schontz**
Fixes #985

### CODE REVIEW

**Comment by paulcpederson** [comment]
Thanks for the pr, but we can't add a non-prefixed class named `active` to our framework like this. CW is used on hundred of sites and the chance that one of those sites would already have a class named `active` is extremely high. This will result in collisions. If a class is related to buttons it should be prefixed by `btn-`. CSS is a global namespace and we need to be responsible.

The other problem is we don't want developers setting their buttons to the active state all the time, and this opens the door to that.

Can you talk about what need this actually solves a bit more? What is the use case for the `active` class? That is a `pseudo` state, so I'm not totally sold on the need to provide a mechanism to recreate that state programatically. Is it just for doc?

**Comment by schontz** [comment]
That's exactly what I need.

**Comment by paulcpederson** [comment]
Cool, we've had a couple requests for something like that now. I'll try to whip that up and cut a release for you.

**Comment by schontz** [comment]
Thank you, very much!

**Pull request closed without merging**
