### PR TITLE
Components/table

### PR DESCRIPTION
**Pull request by julio8a**
* updated font weight for all tables from light (300) to regular (500)
* added `.table-minimal` (from calcite design system website)

#1041

### CODE REVIEW

**Comment by paulcpederson** [comment]
I don't see any changes to font-weights in this pr?

**Comment by julio8a** [comment]
Hmmm not sure what happened there. Should be there now.

**Comment by paulcpederson** [comment]
@julio8a `500` isn't regular, it's medium. We don't actually have a declaration for 500. I would use `400` here.

**Comment by paulcpederson** [comment]
cool, but to be clear, omitting this declaration will make headers `bold` as that is the generally accepted user-agent stylesheet:

screen shot 2019-02-07 at 9 52 04 am

This is fine by me, but wanted to make sure it's what we actually want in the design.

**Comment by julio8a** [comment]
Yeah, it's good. Also ran it by Adam. 👍 thanks for checking.

**Comment by paulcpederson** [comment]
dope

**Pull request merged**
