### PR TITLE
1.0.0

### PR DESCRIPTION
**Pull request by nikolaswise**
@paulcpederson addresses all open issues.

### CODE REVIEW

**Comment by patrickarlt** [comment]
While I understand that SVG icons are probably going to be the future after using them for a bit in some experiments the are actually really hard to use:

1. When you copy/paste them off the site they are always 32x32 pixel which makes them difficult to size properly. For example what if I want to put an icon next to a header? next to a button? in a link? I have to size the icon individually for every use case.
2. When used inside an inline icons they are affected by whitespace. For example the following look different. The extra space is used as padding and is outside our control.
  * `<a><svg>...</svg> Edit</a>`
  * `<a><svg>...</svg>Edit</a>`

After a bit of Googling aroudn I found https://css-tricks.com/svg-sprites-use-better-icon-fonts/ and https://fvsch.com/code/svg-icons/how-to/. based on these articles I would propose updating `.svg-icon` to the following:

```css
.svg-icon {
  display: inline-block; // make sure icons display inline with other elements but have a defined width/height
  width: .875em; // slightly less then the same font size
  height: .875em; // slightly less then the same font size
  vertical-align: -.125em; // offset the image slightly from the top to center it
  padding-right: .125em; // pad the image slightly to the right
  fill: currentColor; // inherit current color
  pointer-events: none; // no pointer events
}
```

**Comment by paulcpederson** [comment]
@patrickarlt my current thinking is to merge this pr, but not release, and then tweak a lot of stuff before going to 1.0.0, so we can handle this then. 

I agree on em-sizing. [Practival SVG](https://abookapart.com/products/practical-svg) also uses similar techniques:

```
 .icon {
     /* make it match the font-size */
     width: 1em;
     height: 1em;
     /* make it match the text color */
     fill: currentColor;
}

```

 I was also interested in moving towards distributing these with an option including definitions so that developers can implement them via the `use:` syntax.

@patrickarlt do you feel that the costs of svg icons outweigh the costs of an icon font?

**Comment by patrickarlt** [comment]
@paulcpederson Currently I don't see much practical benefit to SVG icons over the icon font in terms of actually building a website. I think a few things would need to happen first:

1. We need an SVG icon sprite like https://fvsch.com/code/svg-icons/how-to/#section-sprite so we can include icons like this `<svg><use xlink:href="/calcite-web/icons.svg#map"></use></svg>`
2. Sizing issues need to be fixed

My biggest concern though is migration and update costs. In order to upgrade to Calcite Web 1.0.0 I have to go through the entire developers site and replace every icon. Then we have to do the same thing for all of the other doc processes that feed into the developers website and republish all doc, ect... This would probably take at least a month with little practical benefit for users other then we get to support the latest Calcite Web.

**Comment by paulcpederson** [comment]
@patrickarlt I agree the update cost is immense. That's what I'm facing in my other projects. Wondering if we should leave the font in, maybe deprecated.

**Comment by patrickarlt** [comment]
@paulcpederson I would fully support a seperate stylesheet/import for Icon font compatibility.

**Comment by paulcpederson** [comment]
Yeah the problem is that the icon font introduces an overwhelming amount of tooling, which is why this was such a nice solution as it is pretty much free.

**Comment by paulcpederson** [comment]
@patrickarlt I just talked to @araedavis about this and I'm going to merge this, but *not* do a release yet. Then we'll collaborate on these edits along with a couple other things before releasing.

**Pull request merged**
