### PR TITLE
Removed branding section under patterns

### PR DESCRIPTION
**Pull request by julio8a**

### CODE REVIEW

**Comment by paulcpederson** [comment]
@julio8a we should probably remove the markdown descriptions of these removed patterns as well:

https://github.com/Esri/calcite-web/blob/2.0/docs/source/documentation/components/_esri-logo.md

**Comment by julio8a** [comment]
@paulcpederson, removed.

**Comment by paulcpederson** [comment]
so there is a conflict in the `CHANGELOG`. You can fix by checking out this branch locally, then pulling from `master` and going into the `CHANGELOG` and correcting the merge conflict (`>>>`, etc). Save the file, then add/commit and push up to `julio8a:removed-branding`

**Comment by julio8a** [comment]
@paulcpederson, ah, my bad. Forgot to merge 2.0 first. Done.

**Pull request merged**
